# Generated by Django 4.2.7 on 2023-11-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequests',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp_token', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
            options={
                'db_table': 'otp_request',
            },
        ),
    ]
